### ISSUE TITLE
acmedns is not a registered Caddy module

### ISSUE THREAD

**Issue by mzambrano-tc** [caddy-dns/acmedns#10]
Hi,

I'm not able to use the "add-package" feature in Caddy. The module has to be registered in caddyserver.com as a module.
This is the output I got when I run "caddy add-package https://github.com/caddy-dns/acmedns"

```
2024/10/28 22:20:13.839	INFO	this executable will be replaced	{"path": "/usr/bin/caddy"}
2024/10/28 22:20:13.839	INFO	requesting build	{"os": "linux", "arch": "amd64", "packages": ["https://github.com/caddy-dns/acmedns"]}
Error: download failed: download failed: HTTP 400: https://github.com/caddy-dns/acmedns is not a registered Caddy module package path (id=02872487-4198-4382-bacd-ddfea22f5900)
```

**Comment by sankirta** [comment]
You just need to drop the `https://`. `caddy add-package github.com/caddy-dns/acmedns` works and the module is registered on caddyserver.com.
