### ISSUE TITLE
Fantastic project! Removes the need for custom DNS Provider plugins in Caddy. How to self host acme-dns server?

### ISSUE THREAD

**Issue by gc-ss** [caddy-dns/acmedns#2]
This is a fantastic project!

IIUC, this completely removes the need to have custom DNS Provider plugins in Caddy and can work with any DNS Provider with just this one plugin.

My question is: Is there a detailed guide on `How to self host acme-dns server?` so that I am not dependent on `auth.acme-dns.io`?

**Comment by hvisage** [comment]
You did check https://github.com/joohoi/acme-dns , didn't you?

Scrolling down there is a simple Installation section https://github.com/joohoi/acme-dns/blob/master/README.md#installation

**Comment by sankirta** [comment]
@hvisage is right, there's an installation section at ACME-DNS Github page.
If there's interest, I can share a `docker-compose.yml` and write a short guide on how to set up ACME-DNS server and put Caddy in front of its API in order to protect the API with a token.

**Comment by gc-ss** [comment]
> You did check https://github.com/joohoi/acme-dns , didn't you?

Yes, I did. That setup will have the ACME-DNS instance open to the whole wide world. Also, there are challenges in forwarding port 53 on Ubuntu

> If there's interest, I can share a docker-compose.yml and write a short guide on how to set up ACME-DNS server and put Caddy in front of its API in order to protect the API with a token.

Would really appreciate it. It would be excellent if a user can just `docker-compose up` and have everything setup including "token based auth". Additional notes on how to setup port 53 on Ubuntu would be very helpful

**Comment by sankirta** [comment]
@gc-ss 
As discussed, here's a guide to running ACME-DNS with Caddy in front of its API (adds a token-prefix to URL path): https://github.com/caddy-dns/acmedns/tree/acmedns-hosting/acmedns-hosting :)
