### ISSUE TITLE
Register module on caddyserver.com/download

### ISSUE THREAD

**Issue by bharrisau** [caddy-dns/acmedns#7]
Not sure if it was previously registered or not. But it's not currently available.

I've built with xcaddy and it seems to work well, so seems worth registering for wide use.

**Comment by sankirta** [comment]
Thank you for the suggestion and apologies for the late review.

I don't know how plugins are included in that page but I see that `acmedns` is is currently available by searching for `acmedns`, and the downloaded executable works correctly. It seems that the problem resolved by itself (or was resolved by someone else). :)

**Comment by bharrisau** [comment]
Oh, right, sorry. I eventually registered it myself as I didn't want to set up cross compile for freebsd. I can unregister if you want to take ownership on the caddy site, or else leave it as is.

**Comment by sankirta** [comment]
Ah, makes sense. I looked up how this registration works, I see no harm in you having registered it. You can leave it as is.
